/**
 * DIA Insight Card — "What makes you unique on DNA"
 *
 * A personalized insight card generated by DIA based on heritage,
 * network, skills, and activity. Only visible to the profile owner
 * unless they choose to share it. Pro/Org tier feature.
 * Per PRD Section 2.2: Layer 4 DIA-generated, self only (unless shared).
 */

import React, { useState } from 'react';
import { Share2, Eye, EyeOff, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { UserTier } from '@/types/profileIdentityHub';
import { PROFILE_TIER_GATES } from '@/types/profileIdentityHub';
import { MateMasie } from '@/components/icons/adinkra';

interface DIAInsightCardProps {
  insight: string | null;
  tier: UserTier;
  isOwner: boolean;
  isShared?: boolean;
  onRefresh?: () => void;
  onToggleShare?: () => void;
}

export const DIAInsightCard: React.FC<DIAInsightCardProps> = ({
  insight,
  tier,
  isOwner,
  isShared = false,
  onRefresh,
  onToggleShare,
}) => {
  const [isRefreshing, setIsRefreshing] = useState(false);
  const hasDIAInsight = PROFILE_TIER_GATES[tier].diaInsight;

  // Non-owner viewing: only show if shared
  if (!isOwner && !isShared) return null;

  // Free tier: show upsell
  if (!hasDIAInsight && isOwner) {
    return (
      <div className="rounded-xl p-4 bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-100">
        <div className="flex items-start gap-2">
          <MateMasie className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-semibold text-amber-900">
              What makes you unique on DNA?
            </h3>
            <p className="text-xs text-amber-700 mt-1">
              Upgrade to Pro to unlock DIA-powered insights about your profile,
              network position, and diaspora impact.
            </p>
            <Button
              variant="outline"
              size="sm"
              className="mt-2 text-xs border-amber-300 text-amber-800 hover:bg-amber-100"
            >
              Upgrade to Pro
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // No insight generated yet
  if (!insight && isOwner) {
    return (
      <div className="rounded-xl p-4 bg-gradient-to-br from-emerald-50 to-teal-50 border border-emerald-100">
        <div className="flex items-start gap-2">
          <MateMasie className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-semibold text-emerald-900">
              DIA is learning about you
            </h3>
            <p className="text-xs text-emerald-700 mt-1">
              As you build your profile and engage across the Five C's,
              DIA will generate personalized insights about what makes you unique.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (!insight) return null;

  const handleRefresh = async () => {
    setIsRefreshing(true);
    await onRefresh?.();
    setIsRefreshing(false);
  };

  return (
    <div className="rounded-xl p-4 bg-gradient-to-br from-emerald-50 to-teal-50 border border-emerald-100">
      {/* Header */}
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-1.5">
          <MateMasie className="w-4 h-4 text-emerald-600" />
          <h3 className="text-xs font-semibold text-emerald-800 uppercase tracking-wider">
            DIA Insight
          </h3>
        </div>
        {isOwner && (
          <div className="flex items-center gap-1">
            <button
              className="p-1 rounded hover:bg-emerald-100 transition-colors"
              onClick={onToggleShare}
              title={isShared ? 'Hide from profile' : 'Show on profile'}
            >
              {isShared ? (
                <Eye className="w-3.5 h-3.5 text-emerald-600" />
              ) : (
                <EyeOff className="w-3.5 h-3.5 text-emerald-400" />
              )}
            </button>
            <button
              className={`p-1 rounded hover:bg-emerald-100 transition-colors ${isRefreshing ? 'animate-spin' : ''}`}
              onClick={handleRefresh}
              disabled={isRefreshing}
              title="Refresh insight"
            >
              <RefreshCw className="w-3.5 h-3.5 text-emerald-500" />
            </button>
          </div>
        )}
      </div>

      {/* Insight text */}
      <p className="text-sm text-emerald-900 leading-relaxed">
        {insight}
      </p>

      {/* Shared indicator */}
      {isOwner && (
        <p className="text-[10px] text-emerald-500 mt-2 flex items-center gap-1">
          {isShared ? (
            <>
              <Share2 className="w-3 h-3" />
              Visible on your profile
            </>
          ) : (
            <>
              <EyeOff className="w-3 h-3" />
              Only you can see this
            </>
          )}
        </p>
      )}
    </div>
  );
};

export default DIAInsightCard;
