/**
 * DNA | Notification Intelligence Service
 *
 * DIA-powered notification evaluation, batching, and digest generation.
 * Every notification flows through this service before delivery.
 *
 * Flow:
 * Event Occurs (any C module)
 *   → Notification Event emitted
 *     → This service evaluates: priority, channel, batching, timing
 *       → Renders to appropriate channel(s)
 *         → User interacts (read, dismiss, act)
 *           → Feedback loops to DIA for learning
 */

import { supabase } from '@/integrations/supabase/client';
const db = supabase as any;
import type {
  NotificationV2,
  NotificationCategory,
  NotificationTypeV2,
  NotificationPreferencesV2,
  ChannelDecision,
  DeliveryChannel,
  WeeklyDigest,
  DigestSection,
  NotificationBatch,
  BATCHABLE_TYPES,
  BATCH_WINDOW_MS,
  CATEGORY_DEFAULT_PRIORITY,
} from '@/types/notificationsV2';
import type { NudgePriority } from '@/types/dia';

/**
 * Evaluate a notification and decide priority, channels, and batching.
 * This is the core intelligence function — DIA decides HOW to deliver.
 */
function evaluateNotification(
  notification: Omit<NotificationV2, 'id' | 'channels_delivered' | 'is_read' | 'is_batched' | 'created_at'>,
  userPrefs: NotificationPreferencesV2,
): ChannelDecision {
  const { category, type, priority } = notification;

  // Check quiet hours
  if (isQuietHours(userPrefs)) {
    return {
      channels: ['in_app'], // Only in-app during quiet hours
      reason: 'Quiet hours active - in-app only',
      delay_minutes: 0,
    };
  }

  // Get user's channel preferences for this category
  const categoryPrefs = userPrefs.category_preferences[category];
  if (!categoryPrefs) {
    return { channels: ['in_app'], reason: 'No category preferences' };
  }

  const channels: DeliveryChannel[] = [];

  // In-app is always on (unless explicitly disabled)
  if (categoryPrefs.in_app) channels.push('in_app');

  // Push — only for high priority or time-sensitive
  if (categoryPrefs.push && (priority === 'high' || priority === 'urgent')) {
    channels.push('push');
  }

  // Email — based on preferences and notification importance
  if (categoryPrefs.email && shouldSendEmail(type, priority)) {
    channels.push('email');
  }

  // In-feed — DIA insight cards get this channel
  if (category === 'dia') {
    channels.push('in_feed');
  }

  // If no channels selected, default to in-app
  if (channels.length === 0) {
    channels.push('in_app');
  }

  return {
    channels,
    reason: `${priority} priority ${category} notification`,
  };
}

/**
 * Check if a notification should be batched with existing ones.
 * Returns batch_id if it should be batched, null otherwise.
 */
async function shouldBatch(
  type: NotificationTypeV2,
  userId: string,
): Promise<string | null> {
  // Only batch known batchable types
  const batchableTypes: NotificationTypeV2[] = [
    'post_like', 'post_comment', 'post_reshare', 'profile_view', 'new_follower',
  ];

  if (!batchableTypes.includes(type)) return null;

  // Check for existing recent batch
  const batchWindowStart = new Date(Date.now() - 15 * 60 * 1000).toISOString(); // 15 min window

  const { data: existingBatch } = await supabase
    .from('notifications')
    .select('id, payload')
    .eq('user_id', userId)
    .eq('type', type)
    .gte('created_at', batchWindowStart)
    .order('created_at', { ascending: false })
    .limit(1);

  if (existingBatch && existingBatch.length > 0) {
    return existingBatch[0].id;
  }

  return null;
}

/**
 * Generate a DIA-curated weekly digest for a user.
 * "Here's what you missed this week across your Five C's"
 */
async function generateDigest(userId: string): Promise<WeeklyDigest> {
  const periodEnd = new Date();
  const periodStart = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  const [connectData, conveneData, collaborateData, contributeData, conveyData] =
    await Promise.all([
      getConnectDigest(userId, periodStart.toISOString()),
      getConveneDigest(userId, periodStart.toISOString()),
      getCollaborateDigest(userId, periodStart.toISOString()),
      getContributeDigest(userId, periodStart.toISOString()),
      getConveyDigest(userId, periodStart.toISOString()),
    ]);

  return {
    user_id: userId,
    period_start: periodStart.toISOString(),
    period_end: periodEnd.toISOString(),
    connect_summary: connectData,
    convene_summary: conveneData,
    collaborate_summary: collaborateData,
    contribute_summary: contributeData,
    convey_summary: conveyData,
    top_insight: null, // Generated by DIA trend intelligence
    trending_in_network: [],
    recommended_action: null,
    generated_at: new Date().toISOString(),
  };
}

/**
 * Check if user is currently in quiet hours.
 */
function isQuietHours(prefs: NotificationPreferencesV2): boolean {
  if (!prefs.quiet_hours_enabled) return false;

  const now = new Date();
  // Use simple hour comparison (timezone-aware logic would use prefs.timezone)
  const currentHour = now.getHours();
  const currentMinute = now.getMinutes();
  const currentTime = currentHour * 60 + currentMinute;

  const [startH, startM] = prefs.quiet_hours_start.split(':').map(Number);
  const [endH, endM] = prefs.quiet_hours_end.split(':').map(Number);
  const startTime = startH * 60 + startM;
  const endTime = endH * 60 + endM;

  // Handle overnight quiet hours (e.g., 22:00 - 07:00)
  if (startTime > endTime) {
    return currentTime >= startTime || currentTime < endTime;
  }

  return currentTime >= startTime && currentTime < endTime;
}

// --- Digest section generators ---

async function getConnectDigest(userId: string, since: string): Promise<DigestSection> {
  const { count: newConnections } = await db
    .from('connections')
    .select('*', { count: 'exact', head: true })
    .or(`requester_id.eq.${userId},recipient_id.eq.${userId}`)
    .gte('created_at', since);

  const { count: profileViews } = await db
    .from('notifications')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', userId)
    .eq('type', 'profile_view')
    .gte('created_at', since);

  const count = (newConnections || 0) + (profileViews || 0);
  const highlights: string[] = [];
  if (newConnections) highlights.push(`${newConnections} new connection${newConnections > 1 ? 's' : ''}`);
  if (profileViews) highlights.push(`${profileViews} profile view${profileViews > 1 ? 's' : ''}`);

  return {
    headline: count > 0 ? 'Your network grew this week' : 'Your network was quiet this week',
    count,
    highlights,
  };
}

async function getConveneDigest(userId: string, since: string): Promise<DigestSection> {
  const { count: eventRegistrations } = await db
    .from('event_registrations')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', userId)
    .gte('created_at', since);

  return {
    headline: eventRegistrations ? `${eventRegistrations} event${eventRegistrations > 1 ? 's' : ''} this week` : 'No events this week',
    count: eventRegistrations || 0,
    highlights: [],
  };
}

async function getCollaborateDigest(userId: string, since: string): Promise<DigestSection> {
  const { count: taskUpdates } = await supabase
    .from('space_tasks')
    .select('*', { count: 'exact', head: true })
    .eq('assignee_id', userId)
    .gte('updated_at', since);

  return {
    headline: taskUpdates ? `${taskUpdates} task update${taskUpdates > 1 ? 's' : ''}` : 'Spaces were quiet this week',
    count: taskUpdates || 0,
    highlights: [],
  };
}

async function getContributeDigest(userId: string, since: string): Promise<DigestSection> {
  const { count: opportunityActivity } = await db
    .from('notifications')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', userId)
    .in('type', ['opportunity_match', 'interest_expressed'])
    .gte('created_at', since);

  return {
    headline: opportunityActivity ? `${opportunityActivity} opportunity update${opportunityActivity > 1 ? 's' : ''}` : 'No new opportunity matches',
    count: opportunityActivity || 0,
    highlights: [],
  };
}

async function getConveyDigest(userId: string, since: string): Promise<DigestSection> {
  const { data: posts } = await db
    .from('posts')
    .select('view_count')
    .eq('author_id', userId)
    .gte('created_at', since);

  const totalEngagement = (posts || []).reduce(
    (sum: number, p: { view_count: number | null }) => sum + (p.view_count || 0),
    0,
  );

  const postCount = posts?.length || 0;

  return {
    headline: postCount > 0
      ? `Your content received ${totalEngagement} engagement${totalEngagement !== 1 ? 's' : ''}`
      : 'Share your voice with the network this week',
    count: totalEngagement,
    highlights: postCount > 0 ? [`${postCount} post${postCount > 1 ? 's' : ''} published`] : [],
  };
}

// --- Helper ---

function shouldSendEmail(type: NotificationTypeV2, priority: NudgePriority): boolean {
  // Always email for high/urgent priority
  if (priority === 'high' || priority === 'urgent') return true;

  // Always email for specific types
  const emailTypes: NotificationTypeV2[] = [
    'event_reminder',
    'event_starting_soon',
    'security_alert',
    'payment_confirmation',
    'connection_request',
  ];
  return emailTypes.includes(type);
}

export const notificationIntelligenceService = {
  evaluateNotification,
  shouldBatch,
  generateDigest,
  isQuietHours,
};
