// BD097 / BD039 — the ONE place a provider's dialect is translated into DNA's.
//
// Nominatim and Google both return ISO 3166-1 alpha-2. DNA's canonical origin
// dialect is alpha-3 (BD039) — the same dialect member_heritage speaks. This
// module is the anti-corruption boundary: alpha-2 stops here and never reaches
// the app or the database.
//
// The table is GENERATED from ISO 3166-1 (i18n-iso-countries), never written
// from memory. Packed as fixed-width 5-char records (2 + 3). 250 countries,
// asserted bijective at generation time and re-asserted at module load.

const PACKED =
  'AFAFGALALBDZDZAASASMADANDAOAGOAIAIAAQATAAGATGARARGAMARMAWABWAUAUSATAUTAZAZEBSBHSBHBHRBDBGDBBBRBBYBLRBEBELBZBLZBJBENBMBMUBTBTNBOBOLBABIHBWBWABVBVTBRBRAIOIOTBNBRNBGBGRBFBFABIBDIKHKHMCMCMRCACANCVCPVKYCYMCFCAFTDTCDCLCHLCNCHNCXCXRCCCCKCOCOLKMCOMCGCOGCDCODCKCOKCRCRICICIVHRHRVCUCUBCYCYPCZCZEDKDNKDJDJIDMDMADODOMECECUEGEGYSVSLVGQGNQERERIEEESTETETHFKFLKFOFROFJFJIFIFINFRFRAGFGUFPFPYFTFATFGAGABGMGMBGEGEODEDEUGHGHAGIGIBGRGRCGLGRLGDGRDGPGLPGUGUMGTGTMGNGINGWGNBGYGUYHTHTIHMHMDVAVATHNHNDHKHKGHUHUNISISLININDIDIDNIRIRNIQIRQIEIRLILISRITITAJMJAMJPJPNJOJORKZKAZKEKENKIKIRKPPRKKRKORKWKWTKGKGZLALAOLVLVALBLBNLSLSOLRLBRLYLBYLILIELTLTULULUXMOMACMGMDGMWMWIMYMYSMVMDVMLMLIMTMLTMHMHLMQMTQMRMRTMUMUSYTMYTMXMEXFMFSMMDMDAMCMCOMNMNGMSMSRMAMARMZMOZMMMMRNANAMNRNRUNPNPLNLNLDNCNCLNZNZLNINICNENERNGNGANUNIUNFNFKMPMNPMKMKDNONOROMOMNPKPAKPWPLWPSPSEPAPANPGPNGPYPRYPEPERPHPHLPNPCNPLPOLPTPRTPRPRIQAQATREREUROROURURUSRWRWASHSHNKNKNALCLCAPMSPMVCVCTWSWSMSMSMRSTSTPSASAUSNSENSCSYCSLSLESGSGPSKSVKSISVNSBSLBSOSOMZAZAFGSSGSESESPLKLKASDSDNSRSURSJSJMSZSWZSESWECHCHESYSYRTWTWNTJTJKTZTZATHTHATLTLSTGTGOTKTKLTOTONTTTTOTNTUNTRTURTMTKMTCTCATVTUVUGUGAUAUKRAEAREGBGBRUSUSAUMUMIUYURYUZUZBVUVUTVEVENVNVNMVGVGBVIVIRWFWLFEHESHYEYEMZMZMBZWZWEAXALABQBESCWCUWGGGGYIMIMNJEJEYMEMNEBLBLMMFMAFRSSRBSXSXMSSSSDXKXKK';

function unpack(): Readonly<Record<string, string>> {
  const map: Record<string, string> = {};
  for (let i = 0; i < PACKED.length; i += 5) {
    map[PACKED.slice(i, i + 2)] = PACKED.slice(i + 2, i + 5);
  }
  return map;
}

const ALPHA2_TO_ALPHA3 = unpack();
export const ALPHA3_COUNT = Object.keys(ALPHA2_TO_ALPHA3).length;

// Fail loudly at module load if the table is malformed. A silently truncated
// map would degrade to "country unknown" forever, which is exactly the class of
// silent wrongness this file exists to prevent.
if (PACKED.length % 5 !== 0 || ALPHA3_COUNT !== 250) {
  throw new Error(`[iso-alpha3] table is corrupt: ${ALPHA3_COUNT} entries from ${PACKED.length} chars`);
}

/** alpha-2 (any case) -> alpha-3, or null. Never guesses, never invents. */
export function toAlpha3(alpha2: string | null | undefined): string | null {
  if (!alpha2 || typeof alpha2 !== 'string') return null;
  return ALPHA2_TO_ALPHA3[alpha2.trim().toUpperCase()] ?? null;
}
