import { Sankofa } from '@/components/icons/adinkra';
export const mockProfessionals = [
  {
    id: '1',
    name: 'Dr. Amara Okafor',
    title: 'Senior FinTech Product Manager',
    company: 'Stripe',
    location: 'London, UK',
    origin: 'Lagos, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 890,
    skills: ['Product Strategy', 'Financial Technology', 'Team Leadership'],
    bio: 'Passionate about building financial infrastructure that empowers African businesses globally. 5+ years at top fintech companies.',
    connectionStatus: null,
    recentActivity: 'Published: "The Future of Cross-Border Payments in Africa"',
    isOnline: true,
    mutualConnections: 12
  },
  {
    id: '2',
    name: 'Prof. Kwame Asante',
    title: 'Agricultural Innovation Lead',
    company: 'World Bank Group',
    location: 'Toronto, Canada',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1200,
    skills: ['AgriTech', 'Sustainable Development', 'Research'],
    bio: 'Leading agricultural transformation initiatives across sub-Saharan Africa. PhD in Agricultural Economics.',
    connectionStatus: 'connected',
    recentActivity: 'Shared insights on climate-smart farming',
    isOnline: false,
    mutualConnections: 8
  },
  {
    id: '3',
    name: 'Sarah Mwangi',
    title: 'Impact Investment Principal',
    company: 'TLcom Capital',
    location: 'Nairobi, Kenya',
    origin: 'Nairobi, Kenya',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 750,
    skills: ['Impact Investing', 'Venture Capital', 'ESG'],
    bio: 'Investing in early-stage African startups solving real problems. Former McKinsey consultant with 8+ years experience.',
    connectionStatus: 'pending',
    recentActivity: 'Attended African Startup Summit 2024',
    isOnline: true,
    mutualConnections: 15
  },
  {
    id: '4',
    name: 'Ibrahim Hassan',
    title: 'Tech Entrepreneur',
    company: 'Flutterwave',
    location: 'San Francisco, USA',
    origin: 'Cairo, Egypt',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4200,
    connections: 980,
    skills: ['Fintech', 'Entrepreneurship', 'Market Expansion'],
    bio: 'Building payment solutions for Africa. Previously scaled tech teams across 3 continents.',
    connectionStatus: null,
    recentActivity: 'Launched new payment gateway for SMEs',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '5',
    name: 'Dr. Fatima Al-Rashid',
    title: 'Climate Tech Researcher',
    company: 'MIT',
    location: 'Boston, USA',
    origin: 'Marrakech, Morocco',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 650,
    skills: ['Climate Technology', 'Renewable Energy', 'Policy'],
    bio: 'PhD researcher focusing on scalable climate solutions for MENA and Sub-Saharan Africa.',
    connectionStatus: null,
    recentActivity: 'Published research on solar energy adoption',
    isOnline: false,
    mutualConnections: 7
  },
  {
    id: '6',
    name: 'Kofi Mensah',
    title: 'Digital Health Innovator',
    company: 'mPharma',
    location: 'Accra, Ghana',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
    followers: 1850,
    connections: 420,
    skills: ['Healthcare Technology', 'Digital Health', 'Operations'],
    bio: 'Revolutionizing healthcare access across Africa through technology and innovative supply chain solutions.',
    connectionStatus: 'connected',
    recentActivity: 'Expanded operations to 3 new countries',
    isOnline: true,
    mutualConnections: 5
  },
  // 15 Additional Diverse Diaspora Professionals
  {
    id: '7',
    name: 'Marcus Johnson',
    title: 'Cultural Heritage Director',
    company: 'Smithsonian Institution',
    location: 'Washington DC, USA',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    followers: 3200,
    connections: 780,
    skills: ['Cultural Preservation', 'Museum Curation', 'Educational Programs'],
    bio: 'Dedicated to preserving and showcasing African American history and its connections to the African continent.',
    connectionStatus: null,
    recentActivity: 'Launched "Diaspora Connections" exhibition',
    isOnline: true,
    mutualConnections: 18
  },
  {
    id: '8',
    name: 'Dr. Mariam Touré-Williams',
    title: 'Global Health Equity Specialist', 
    company: 'WHO',
    location: 'Geneva, Switzerland',
    origin: 'Bamako, Mali / Detroit, USA',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 4890,
    connections: 1340,
    skills: ['Public Health', 'Health Equity', 'International Development'],
    bio: 'Mali-born, Detroit-raised physician working to eliminate health disparities across Africa and the diaspora.',
    connectionStatus: 'connected',
    recentActivity: 'Published maternal health study across 12 countries',
    isOnline: false,
    mutualConnections: 31
  },
  {
    id: '9',
    name: 'Keisha Baptiste',
    title: 'Sustainable Fashion Entrepreneur',
    company: 'Caribbean Threads Collective',
    location: 'Port of Spain, Trinidad',
    origin: 'Afro-Caribbean Heritage',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 2670,
    connections: 540,
    skills: ['Sustainable Fashion', 'Ethical Manufacturing', 'Cultural Design'],
    bio: 'Bridging Caribbean and African textile traditions while building sustainable fashion supply chains.',
    connectionStatus: 'pending',
    recentActivity: 'Launched partnership with Ghana textile producers',
    isOnline: true,
    mutualConnections: 9
  },
  {
    id: '10',
    name: 'David Chen',
    title: 'Africa Tech Investment Director',
    company: 'Andreessen Horowitz',
    location: 'Silicon Valley, USA',
    origin: 'Ally - Chinese American',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 5230,
    connections: 1450,
    skills: ['Venture Capital', 'African Tech Ecosystem', 'Strategic Partnerships'],
    bio: 'Passionate ally investing in African tech startups. Focused on building bridges between Silicon Valley and African innovation.',
    connectionStatus: null,
    recentActivity: 'Led $15M Series A in Lagos-based startup',
    isOnline: true,
    mutualConnections: 28
  },
  {
    id: '11',
    name: 'Aisha Omar-Jackson',
    title: 'Renewable Energy Engineer',
    company: 'Tesla Energy',
    location: 'Austin, USA',
    origin: 'Mogadishu, Somalia / Atlanta, USA',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 3890,
    connections: 920,
    skills: ['Solar Engineering', 'Grid Infrastructure', 'Energy Storage'],
    bio: 'Somali-American engineer developing clean energy solutions for off-grid communities in Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Deployed solar microgrids in 5 Kenyan villages',
    isOnline: true,
    mutualConnections: 16
  },
  {
    id: '12',
    name: 'Roberto Fernandez',
    title: 'Afro-Latin Cultural Ambassador',
    company: 'OAS Cultural Programs',
    location: 'Bogotá, Colombia',
    origin: 'Afro-Colombian Heritage',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 680,
    skills: ['Cultural Diplomacy', 'Afro-Latin Studies', 'Community Organizing'],
    bio: 'Celebrating and preserving Afro-Latin connections to Africa through cultural exchange programs.',
    connectionStatus: null,
    recentActivity: 'Organized Pan-African Cultural Festival',
    isOnline: false,
    mutualConnections: 12
  },
  {
    id: '13',
    name: 'Dr. Thandiwe Nyong',
    title: 'AI Ethics Researcher',
    company: 'Google DeepMind',
    location: 'London, UK',
    origin: 'Cape Town, South Africa',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 6780,
    connections: 1890,
    skills: ['Artificial Intelligence', 'Ethics', 'Algorithmic Bias'],
    bio: 'Ensuring AI systems are fair and inclusive for African and global South communities.',
    connectionStatus: 'pending',
    recentActivity: 'Published "AI Bias in African Languages" paper',
    isOnline: true,
    mutualConnections: 45
  },
  {
    id: '14',
    name: 'Jamal Washington',
    title: 'Sports Development Director',
    company: 'NBA Africa',
    location: 'Johannesburg, South Africa',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4560,
    connections: 1120,
    skills: ['Sports Management', 'Youth Development', 'International Relations'],
    bio: 'African American executive developing basketball talent across Africa and connecting youth with opportunities.',
    connectionStatus: 'connected',
    recentActivity: 'Launched youth academy in Lagos',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '15',
    name: 'Dr. Maria Santos',
    title: 'Tropical Medicine Specialist',
    company: 'Médecins Sans Frontières',
    location: 'São Paulo, Brazil',
    origin: 'Afro-Brazilian Heritage',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 890,
    skills: ['Tropical Medicine', 'Infectious Diseases', 'Global Health'],
    bio: 'Afro-Brazilian physician working on health initiatives across Portuguese-speaking Africa.',
    connectionStatus: null,
    recentActivity: 'Led malaria prevention program in Mozambique',
    isOnline: false,
    mutualConnections: 19
  },
  {
    id: '16',
    name: 'Sarah Mitchell',
    title: 'Impact Storyteller & Documentarian',
    company: 'Independent',
    location: 'Toronto, Canada',
    origin: 'Cape Town, South Africa',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b35d4e1c?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 670,
    skills: ['Documentary Film', 'Social Impact', 'Visual Storytelling'],
    bio: 'South African documentary filmmaker dedicated to amplifying African diaspora stories and social impact initiatives.',
    connectionStatus: 'pending',
    recentActivity: 'Released "Bridges Across Waters" documentary',
    isOnline: true,
    mutualConnections: 14
  },
  {
    id: '17',
    name: 'Emmanuel Owusu-Ansah',
    title: 'Blockchain Infrastructure Lead',
    company: 'Polygon',
    location: 'Remote (Ghana)',
    origin: 'Kumasi, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1340,
    skills: ['Blockchain', 'DeFi', 'Cryptocurrency'],
    bio: 'Building decentralized financial infrastructure to connect African economies with global markets.',
    connectionStatus: 'connected',
    recentActivity: 'Launched DeFi protocol for cross-border remittances',
    isOnline: true,
    mutualConnections: 33
  },
  {
    id: '18',
    name: 'Michelle Pierre-Louis',
    title: 'Climate Justice Advocate',
    company: 'Caribbean Climate Alliance',
    location: 'Miami, USA',
    origin: 'Haitian-American Heritage',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 4230,
    connections: 980,
    skills: ['Climate Advocacy', 'Environmental Justice', 'Policy Development'],
    bio: 'Haitian-American advocate connecting Caribbean and African communities on climate resilience strategies.',
    connectionStatus: null,
    recentActivity: 'Organized Pan-African Climate Summit',
    isOnline: false,
    mutualConnections: 27
  },
  {
    id: '19',
    name: 'Dr. Ahmed Osman',
    title: 'EdTech Innovation Director',
    company: 'UNICEF',
    location: 'Dubai, UAE',
    origin: 'Khartoum, Sudan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 3780,
    connections: 1120,
    skills: ['Educational Technology', 'Digital Learning', 'Child Development'],
    bio: 'Sudanese educator leveraging technology to improve learning outcomes for children across Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Deployed digital classrooms in refugee camps',
    isOnline: true,
    mutualConnections: 21
  },
  {
    id: '20',
    name: 'Amina Johnson-Clarke',
    title: 'Social Entrepreneurship Professor',
    company: 'Howard University',
    location: 'Washington DC, USA',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 3990,
    connections: 850,
    skills: ['Social Innovation', 'Entrepreneurship', 'Academic Research'],
    bio: 'African American professor mentoring next generation of social entrepreneurs focused on African development.',
    connectionStatus: 'pending',
    recentActivity: 'Published "Diaspora Innovation Ecosystems" study',
    isOnline: true,
    mutualConnections: 38
  },
  {
    id: '21',
    name: 'Jean-Baptiste Mokoko',
    title: 'Circular Economy Consultant',
    company: 'Ellen MacArthur Foundation',
    location: 'Paris, France',
    origin: 'Brazzaville, Congo',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 2560,
    connections: 720,
    skills: ['Circular Economy', 'Sustainability Consulting', 'Resource Management'],
    bio: 'Congolese sustainability expert helping African businesses transition to circular economy models.',
    connectionStatus: null,
    recentActivity: 'Launched waste-to-value initiative in Cameroon',
    isOnline: false,
    mutualConnections: 15
  },
  // 20 Additional Professionals (IDs 22-41)
  {
    id: '22',
    name: 'Dr. Chimamanda Adichie-Brown',
    title: 'Digital Media Strategist',
    company: 'Netflix',
    location: 'Los Angeles, USA',
    origin: 'Enugu, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 7890,
    connections: 2340,
    skills: ['Content Strategy', 'Digital Marketing', 'African Storytelling'],
    bio: 'Nigerian storyteller revolutionizing African narrative representation in global streaming content.',
    connectionStatus: 'connected',
    recentActivity: 'Launched African Stories Initiative reaching 50M viewers',
    isOnline: true,
    mutualConnections: 42
  },
  {
    id: '23',
    name: 'Kwame Nkrumah Jr.',
    title: 'Infrastructure Finance Director',
    company: 'African Development Bank',
    location: 'Abidjan, Ivory Coast',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 4560,
    connections: 1890,
    skills: ['Infrastructure Finance', 'Project Management', 'Economic Development'],
    bio: 'Financing transformative infrastructure projects across Africa, following his father\'s vision of continental unity.',
    connectionStatus: null,
    recentActivity: 'Secured $2B funding for trans-African railway project',
    isOnline: false,
    mutualConnections: 28
  },
  {
    id: '24',
    name: 'Zara Okonkwo',
    title: 'Aerospace Engineer',
    company: 'SpaceX',
    location: 'Hawthorne, USA',
    origin: 'Aba, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 6780,
    connections: 1567,
    skills: ['Sankofa Engineering', 'Satellite Technology', 'Space Systems'],
    bio: 'Nigerian aerospace engineer working on satellite technology to connect remote African communities.',
    connectionStatus: 'pending',
    recentActivity: 'Led deployment of internet satellites over rural Nigeria',
    isOnline: true,
    mutualConnections: 35
  },
  {
    id: '25',
    name: 'Tariq Al-Mahmoud',
    title: 'Renewable Energy Economist',
    company: 'International Renewable Energy Agency',
    location: 'Abu Dhabi, UAE',
    origin: 'Tunis, Tunisia',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 3890,
    connections: 1234,
    skills: ['Energy Economics', 'Solar Technology', 'Policy Analysis'],
    bio: 'Tunisian economist driving renewable energy adoption across North and Sub-Saharan Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Published MENA-Africa clean energy transition roadmap',
    isOnline: true,
    mutualConnections: 29
  },
  {
    id: '26',
    name: 'Nomsa Dlamini',
    title: 'Mining Safety Innovation Lead',
    company: 'Anglo American',
    location: 'Johannesburg, South Africa',
    origin: 'Mbabane, Eswatini',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 890,
    skills: ['Mining Technology', 'Safety Engineering', 'Innovation Management'],
    bio: 'Swazi engineer revolutionizing mining safety across Southern Africa through AI and robotics.',
    connectionStatus: null,
    recentActivity: 'Deployed autonomous safety robots in 12 mines',
    isOnline: false,
    mutualConnections: 18
  },
  {
    id: '27',
    name: 'Malik Thompson-Asante',
    title: 'Urban Planning Architect',
    company: 'UN-Habitat',
    location: 'Nairobi, Kenya',
    origin: 'African American / Ghanaian Heritage',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1456,
    skills: ['Urban Planning', 'Sustainable Design', 'Smart Cities'],
    bio: 'Mixed-heritage architect designing climate-resilient cities across Africa with community-centered approaches.',
    connectionStatus: 'connected',
    recentActivity: 'Designed resilient housing for 100K Nairobi residents',
    isOnline: true,
    mutualConnections: 33
  },
  {
    id: '28',
    name: 'Dr. Youssef Ben-Salem',
    title: 'Artificial Intelligence Researcher',
    company: 'Google AI',
    location: 'Montreal, Canada',
    origin: 'Casablanca, Morocco',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 8900,
    connections: 2567,
    skills: ['Machine Learning', 'Natural Language Processing', 'AI Ethics'],
    bio: 'Moroccan AI researcher developing multilingual models for African languages and contexts.',
    connectionStatus: 'pending',
    recentActivity: 'Open-sourced African language AI models for 20 languages',
    isOnline: true,
    mutualConnections: 47
  },
  {
    id: '29',
    name: 'Esther Nakamura-Banda',
    title: 'Agricultural Biotechnology Lead',
    company: 'CGIAR',
    location: 'Lusaka, Zambia',
    origin: 'Japanese-Zambian Heritage',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 4230,
    connections: 1123,
    skills: ['Biotechnology', 'Crop Science', 'Food Security'],
    bio: 'Japanese-Zambian scientist developing drought-resistant crops for Southern African farmers.',
    connectionStatus: 'connected',
    recentActivity: 'Released drought-resistant maize varieties to 500K farmers',
    isOnline: false,
    mutualConnections: 26
  },
  {
    id: '30',
    name: 'Amara Diallo-Smith',
    title: 'Pharmaceutical Research Director',
    company: 'Johnson & Johnson',
    location: 'New Brunswick, USA',
    origin: 'Conakry, Guinea / Atlanta, USA',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 6780,
    connections: 1890,
    skills: ['Drug Development', 'Clinical Research', 'Global Health'],
    bio: 'Guinean-American researcher developing treatments for tropical diseases affecting African populations.',
    connectionStatus: null,
    recentActivity: 'Advanced malaria vaccine to Phase III trials',
    isOnline: true,
    mutualConnections: 39
  },
  {
    id: '31',
    name: 'Sipho van der Merwe',
    title: 'Wine Innovation Specialist',
    company: 'Stellenbosch Wine Estates',
    location: 'Cape Town, South Africa',
    origin: 'Cape Town, South Africa',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b35d4e1c?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 890,
    skills: ['Viticulture', 'Wine Technology', 'Export Strategy'],
    bio: 'White South African wine specialist promoting African wines globally while supporting Black wine farmers.',
    connectionStatus: 'connected',
    recentActivity: 'Launched mentorship program for 200 emerging Black vintners',
    isOnline: true,
    mutualConnections: 21
  },
  {
    id: '32',
    name: 'Fatima Kone-Williams',
    title: 'Fashion Tech Entrepreneur',
    company: 'Ankara Labs',
    location: 'New York, USA',
    origin: 'Bamako, Mali / Harlem, USA',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 12400,
    connections: 3890,
    skills: ['Fashion Technology', 'E-commerce', 'African Textiles'],
    bio: 'Malian-American entrepreneur connecting African textile artisans with global fashion markets through technology.',
    connectionStatus: 'pending',
    recentActivity: 'Platform generated $50M for 10K African artisans',
    isOnline: true,
    mutualConnections: 58
  },
  {
    id: '33',
    name: 'Dr. Chike Okafor-Rodriguez',
    title: 'Neurosurgeon & Medical Innovator',
    company: 'Mayo Clinic',
    location: 'Rochester, USA',
    origin: 'Lagos, Nigeria / Dominican Republic',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1567,
    skills: ['Neurosurgery', 'Medical Devices', 'Telemedicine'],
    bio: 'Nigerian-Dominican neurosurgeon developing low-cost surgical robotics for African hospitals.',
    connectionStatus: 'connected',
    recentActivity: 'Performed first remote surgery between US and Lagos',
    isOnline: false,
    mutualConnections: 34
  },
  {
    id: '34',
    name: 'Aaliyah Hassan-Chen',
    title: 'Quantum Computing Researcher',
    company: 'IBM Research',
    location: 'Yorktown Heights, USA',
    origin: 'Somali-Chinese American Heritage',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 7890,
    connections: 2134,
    skills: ['Quantum Computing', 'Physics', 'Cryptography'],
    bio: 'Somali-Chinese quantum physicist developing encryption solutions for secure African digital infrastructure.',
    connectionStatus: 'pending',
    recentActivity: 'Published breakthrough in quantum encryption for developing markets',
    isOnline: true,
    mutualConnections: 41
  },
  {
    id: '35',
    name: 'James de Wet',
    title: 'Conservation Technology Director',
    company: 'WWF Africa',
    location: 'Cape Town, South Africa',
    origin: 'Pretoria, South Africa',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4560,
    connections: 1234,
    skills: ['Conservation Technology', 'Wildlife Protection', 'Drone Technology'],
    bio: 'Afrikaner conservationist using cutting-edge technology to protect African wildlife and support local communities.',
    connectionStatus: 'connected',
    recentActivity: 'Deployed AI anti-poaching system across 15 parks',
    isOnline: true,
    mutualConnections: 27
  },
  {
    id: '36',
    name: 'Aminata Traore-Kim',
    title: 'Digital Banking Innovation Lead',
    company: 'Goldman Sachs',
    location: 'London, UK',
    origin: 'Dakar, Senegal / Seoul, South Korea',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 8900,
    connections: 2567,
    skills: ['Digital Banking', 'Financial Inclusion', 'Mobile Payments'],
    bio: 'Senegalese-Korean banking executive revolutionizing financial access across Francophone Africa.',
    connectionStatus: null,
    recentActivity: 'Launched mobile banking serving 5M West Africans',
    isOnline: false,
    mutualConnections: 43
  },
  {
    id: '37',
    name: 'Dr. Nkem Ifejika',
    title: 'Climate Adaptation Scientist',
    company: 'IPCC',
    location: 'Geneva, Switzerland',
    origin: 'Enugu, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 6780,
    connections: 1890,
    skills: ['Climate Science', 'Adaptation Planning', 'Policy Research'],
    bio: 'Leading climate scientist developing adaptation strategies for African coastal cities and agriculture.',
    connectionStatus: 'connected',
    recentActivity: 'Co-authored IPCC Africa climate adaptation guidelines',
    isOnline: true,
    mutualConnections: 36
  },
  {
    id: '38',
    name: 'Omar Al-Rashid-Jones',
    title: 'Renewable Energy Entrepreneur',
    company: 'SolarAfrica Ventures',
    location: 'Accra, Ghana',
    origin: 'Egyptian-British Heritage',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1456,
    skills: ['Solar Energy', 'Energy Storage', 'Impact Investing'],
    bio: 'Egyptian-British entrepreneur building solar infrastructure across West Africa, powering rural communities.',
    connectionStatus: 'pending',
    recentActivity: 'Raised $100M Series B for off-grid solar expansion',
    isOnline: true,
    mutualConnections: 31
  },
  {
    id: '39',
    name: 'Thandiwe Moyo-Patel',
    title: 'EdTech Product Manager',
    company: 'Coursera',
    location: 'Mountain View, USA',
    origin: 'Harare, Zimbabwe / Mumbai, India',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 4230,
    connections: 1123,
    skills: ['EdTech', 'Product Strategy', 'Online Learning'],
    bio: 'Zimbabwean-Indian product leader democratizing higher education access across Africa through online platforms.',
    connectionStatus: 'connected',
    recentActivity: 'Launched free university courses for 100K African students',
    isOnline: false,
    mutualConnections: 28
  },
  {
    id: '40',
    name: 'Kofi Andersson',
    title: 'Sustainable Architecture Lead',
    company: 'Foster + Partners',
    location: 'London, UK',
    origin: 'Ghanaian-Swedish Heritage',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 7890,
    connections: 2134,
    skills: ['Sustainable Architecture', 'Green Building', 'Urban Design'],
    bio: 'Ghanaian-Swedish architect designing carbon-neutral buildings across Africa using local materials and techniques.',
    connectionStatus: 'connected',
    recentActivity: 'Completed net-zero embassy building in Accra',
    isOnline: true,
    mutualConnections: 45
  },
  {
    id: '41',
    name: 'Amara van Schalkwyk',
    title: 'Marine Conservation Biologist',
    company: 'Sea Shepherd Africa',
    location: 'Cape Town, South Africa',
    origin: 'Cape Town, South Africa',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b35d4e1c?w=150&h=150&fit=crop&crop=face',
    followers: 3890,
    connections: 1012,
    skills: ['Marine Biology', 'Conservation', 'Ocean Protection'],
    bio: 'White South African marine biologist protecting African coastal ecosystems while empowering local fishing communities.',
    connectionStatus: 'pending',
    recentActivity: 'Established 5 new marine protected areas along SA coast',
    isOnline: true,
    mutualConnections: 23
  },
  // Additional 20 professionals for expanded diversity
  {
    id: '42',
    name: 'Dr. Zanele Nkomo',
    title: 'Medical Research Director',
    company: 'African Health Innovation Hub',
    location: 'Harare, Zimbabwe',
    origin: 'Bulawayo, Zimbabwe', 
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 1890,
    connections: 567,
    skills: ['Medical Research', 'Public Health', 'Healthcare Innovation'],
    bio: 'Leading breakthrough research in tropical diseases and affordable healthcare solutions for rural communities.',
    connectionStatus: null,
    recentActivity: 'Published research on malaria prevention strategies',
    isOnline: true,
    mutualConnections: 15
  },
  {
    id: '43',
    name: 'Ahmed El-Khoury',
    title: 'Blockchain Infrastructure Lead',
    company: 'Cairo Tech Solutions',
    location: 'Cairo, Egypt',
    origin: 'Alexandria, Egypt',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 890,
    skills: ['Blockchain', 'Cryptocurrency', 'DeFi', 'Smart Contracts'],
    bio: 'Building decentralized financial infrastructure for the MENA region. Former Microsoft engineer with 8+ years blockchain experience.',
    connectionStatus: 'connected',
    recentActivity: 'Launched new DeFi protocol for African markets',
    isOnline: false,
    mutualConnections: 23
  },
  {
    id: '44',
    name: 'Comfort Okafor',
    title: 'Social Impact Consultant',
    company: 'Gates Foundation',
    location: 'Seattle, USA',
    origin: 'Enugu, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 3120,
    connections: 1450,
    skills: ['Social Impact', 'Program Management', 'Development Finance'],
    bio: 'Designing scalable interventions for poverty alleviation and women empowerment across sub-Saharan Africa.',
    connectionStatus: 'pending',
    recentActivity: 'Spoke at Global Development Summit 2024',
    isOnline: true,
    mutualConnections: 31
  },
  {
    id: '45',
    name: 'Mamadou Traore',
    title: 'Climate Finance Specialist',
    company: 'World Bank',
    location: 'Dakar, Senegal',
    origin: 'Bamako, Mali',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 1670,
    connections: 723,
    skills: ['Climate Finance', 'Green Bonds', 'ESG Investment'],
    bio: 'Mobilizing climate finance for renewable energy projects across West Africa. MBA from INSEAD.',
    connectionStatus: null,
    recentActivity: 'Closed €50M green bond for solar installations',
    isOnline: false,
    mutualConnections: 18
  },
  {
    id: '46',
    name: 'Dr. Rehema Mwalimu',
    title: 'Digital Education Pioneer',
    company: 'UNESCO',
    location: 'Paris, France',
    origin: 'Mwanza, Tanzania',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 1123,
    skills: ['Educational Technology', 'Digital Literacy', 'Youth Development'],
    bio: 'Revolutionizing education access through digital platforms. Leading UNESCO\'s digital education initiatives for Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Launched digital literacy program in 12 countries',
    isOnline: true,
    mutualConnections: 27
  },
  {
    id: '47',
    name: 'Youssef Benali',
    title: 'Aerospace Engineer',
    company: 'Morocco Space Agency',
    location: 'Rabat, Morocco',
    origin: 'Casablanca, Morocco',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 1456,
    connections: 634,
    skills: ['Aerospace Engineering', 'Satellite Technology', 'Space Systems'],
    bio: 'Developing satellite technology for agricultural monitoring and climate research. Former NASA contractor.',
    connectionStatus: null,
    recentActivity: 'Successfully launched Morocco\'s agricultural monitoring satellite',
    isOnline: false,
    mutualConnections: 11
  },
  {
    id: '48',
    name: 'Grace Achieng',
    title: 'Fintech Product Manager',
    company: 'Safaricom',
    location: 'Nairobi, Kenya',
    origin: 'Kisumu, Kenya',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 1890,
    connections: 789,
    skills: ['Product Management', 'Mobile Payments', 'User Experience'],
    bio: 'Leading next-generation mobile financial services. Key architect behind M-Pesa\'s expansion across East Africa.',
    connectionStatus: 'pending',
    recentActivity: 'Launched new micro-lending feature for SMEs',
    isOnline: true,
    mutualConnections: 19
  },
  {
    id: '49',
    name: 'Dr. Sipho Mthembu',
    title: 'Renewable Energy Researcher',
    company: 'University of Cape Town',
    location: 'Cape Town, South Africa',
    origin: 'Durban, South Africa',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 2134,
    connections: 967,
    skills: ['Solar Energy', 'Energy Storage', 'Grid Integration'],
    bio: 'Pioneering affordable solar solutions for townships. Leading South Africa\'s transition to renewable energy.',
    connectionStatus: 'connected',
    recentActivity: 'Published breakthrough research on perovskite solar cells',
    isOnline: false,
    mutualConnections: 24
  },
  {
    id: '50',
    name: 'Amira Kassem',
    title: 'Digital Marketing Strategist',
    company: 'Jumia Technologies',
    location: 'Lagos, Nigeria',
    origin: 'Cairo, Egypt',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 1723,
    connections: 892,
    skills: ['Digital Marketing', 'E-commerce', 'Growth Hacking'],
    bio: 'Scaling e-commerce across Africa through data-driven marketing strategies. Former Google marketing manager.',
    connectionStatus: null,
    recentActivity: 'Led 200% growth in West African user acquisition',
    isOnline: true,
    mutualConnections: 16
  },
  {
    id: '51',
    name: 'Prof. Kwaku Appiah',
    title: 'Biotechnology Researcher',
    company: 'University of Ghana',
    location: 'Accra, Ghana',
    origin: 'Kumasi, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 1567,
    connections: 678,
    skills: ['Biotechnology', 'Genetic Engineering', 'Agricultural Science'],
    bio: 'Developing drought-resistant crop varieties for West African farmers. Published 50+ peer-reviewed papers.',
    connectionStatus: 'connected',
    recentActivity: 'Received grant for cassava genetic improvement project',
    isOnline: false,
    mutualConnections: 13
  },
  {
    id: '52',
    name: 'Fatou Diop',
    title: 'Logistics Innovation Manager',
    company: 'DHL Supply Chain',
    location: 'Dubai, UAE',
    origin: 'Dakar, Senegal',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 1234,
    connections: 567,
    skills: ['Supply Chain', 'Logistics', 'Operations Management'],
    bio: 'Optimizing supply chains for African markets. Reduced delivery times by 40% across 15 countries.',
    connectionStatus: 'pending',
    recentActivity: 'Implemented AI-powered route optimization system',
    isOnline: true,
    mutualConnections: 21
  },
  {
    id: '53',
    name: 'Dr. Tadesse Gebru',
    title: 'AI Ethics Researcher',
    company: 'Stanford University',
    location: 'Palo Alto, USA',
    origin: 'Addis Ababa, Ethiopia',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 3456,
    connections: 1567,
    skills: ['Artificial Intelligence', 'Ethics', 'Machine Learning'],
    bio: 'Leading research on ethical AI systems and algorithmic bias. Former Google AI researcher and ethics advocate.',
    connectionStatus: 'connected',
    recentActivity: 'Keynoted at AI Ethics Summit 2024',
    isOnline: false,
    mutualConnections: 29
  },
  {
    id: '54',
    name: 'Chipo Mutasa',
    title: 'Mining Engineer',
    company: 'Anglo American',
    location: 'Johannesburg, South Africa',
    origin: 'Harare, Zimbabwe',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 1678,
    connections: 723,
    skills: ['Mining Engineering', 'Sustainable Mining', 'Project Management'],
    bio: 'Implementing sustainable mining practices across Southern Africa. Champion of women in mining initiatives.',
    connectionStatus: null,
    recentActivity: 'Led successful mine digitization project in Botswana',
    isOnline: true,
    mutualConnections: 17
  },
  {
    id: '55',
    name: 'Moussa Sanogo',
    title: 'Telecommunications Executive',
    company: 'Orange Middle East & Africa',
    location: 'Abidjan, Côte d\'Ivoire',
    origin: 'Bouaké, Côte d\'Ivoire',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 2234,
    connections: 1123,
    skills: ['Telecommunications', '5G Networks', 'Digital Infrastructure'],
    bio: 'Expanding mobile connectivity across West Africa. Leading 5G rollout in 8 African countries.',
    connectionStatus: 'pending',
    recentActivity: 'Launched rural connectivity initiative reaching 2M people',
    isOnline: false,
    mutualConnections: 25
  },
  {
    id: '56',
    name: 'Dr. Lilian Ochieng',
    title: 'Pharmaceutical Researcher',
    company: 'Novartis Institute',
    location: 'Basel, Switzerland',
    origin: 'Nairobi, Kenya',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 1789,
    connections: 834,
    skills: ['Pharmaceutical Research', 'Drug Development', 'Clinical Trials'],
    bio: 'Developing affordable medicines for tropical diseases. Leading clinical trials for new malaria treatments.',
    connectionStatus: 'connected',
    recentActivity: 'Received FDA approval for new antimalarial drug',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '57',
    name: 'Hassan Mwalimu',
    title: 'Renewable Energy Consultant',
    company: 'International Energy Agency',
    location: 'Vienna, Austria',
    origin: 'Stone Town, Tanzania',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 1456,
    connections: 678,
    skills: ['Energy Policy', 'Solar Power', 'Wind Energy'],
    bio: 'Advising African governments on renewable energy transitions. Former lead consultant for East Africa Power Pool.',
    connectionStatus: null,
    recentActivity: 'Completed feasibility study for regional power grid',
    isOnline: false,
    mutualConnections: 14
  },
  {
    id: '58',
    name: 'Aissatou Ba',
    title: 'Fashion Tech Entrepreneur',
    company: 'AfriStyle Digital',
    location: 'Paris, France',
    origin: 'Conakry, Guinea',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 2567,
    connections: 1234,
    skills: ['Fashion Technology', 'E-commerce', 'Brand Development'],
    bio: 'Digitalizing African fashion brands for global markets. Created platform connecting 500+ African designers worldwide.',
    connectionStatus: 'connected',
    recentActivity: 'Closed Series A funding for African fashion marketplace',
    isOnline: true,
    mutualConnections: 28
  },
  {
    id: '59',
    name: 'Dr. Kofi Asante',
    title: 'Urban Planning Specialist',
    company: 'UN-Habitat',
    location: 'Nairobi, Kenya',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 1890,
    connections: 823,
    skills: ['Urban Planning', 'Smart Cities', 'Sustainable Development'],
    bio: 'Designing sustainable cities for rapid African urbanization. Leading smart city initiatives in 10 African capitals.',
    connectionStatus: 'pending',
    recentActivity: 'Launched Kampala Smart City master plan',
    isOnline: false,
    mutualConnections: 20
  },
  {
    id: '60',
    name: 'Nomsa Dlamini',
    title: 'Investment Banking Director',
    company: 'Goldman Sachs',
    location: 'London, UK',
    origin: 'Mbabane, Eswatini',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 3234,
    connections: 1567,
    skills: ['Investment Banking', 'Capital Markets', 'Infrastructure Finance'],
    bio: 'Structuring major infrastructure deals across Africa. Led $2B financing for renewable energy projects.',
    connectionStatus: 'connected',
    recentActivity: 'Closed largest green bond issuance in African history',
    isOnline: true,
    mutualConnections: 35
  },
  {
    id: '61',
    name: 'Omar Cherif',
    title: 'Cybersecurity Expert',
    company: 'Kaspersky Lab',
    location: 'Tunis, Tunisia',
    origin: 'Sfax, Tunisia',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 1567,
    connections: 723,
    skills: ['Cybersecurity', 'Information Security', 'Threat Analysis'],
    bio: 'Protecting African businesses from cyber threats. Leading cybersecurity training programs across MENA region.',
    connectionStatus: null,
    recentActivity: 'Launched African Cybersecurity Excellence Center',
    isOnline: false,
    mutualConnections: 16
  }
];

export type MockProfessional = typeof mockProfessionals[0];