// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-profiles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
async function restGet(path) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const res = await fetch(`${url}/rest/v1/${path}`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` }
  });
  if (!res.ok) throw new Error(`Supabase ${res.status}: ${await res.text()}`);
  return res.json();
}
var search_profiles_default = defineTool({
  name: "search_profiles",
  title: "Search DNA member profiles",
  description: "Search public DNA (Diaspora Network of Africa) member profiles by name, username, or headline. Returns basic public info and a shareable /dna/<username> profile link.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Name, username, or keyword to search for."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const q = encodeURIComponent(query);
    const n = limit ?? 10;
    const path = `profiles?select=username,full_name,headline,avatar_url,city,country&or=(username.ilike.*${q}*,full_name.ilike.*${q}*,headline.ilike.*${q}*)&limit=${n}`;
    const rows = await restGet(path);
    const results = rows.map((r) => ({
      ...r,
      profile_url: r.username ? `https://diasporanetwork.africa/dna/${r.username}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_events_default = defineTool2({
  name: "list_upcoming_events",
  title: "List upcoming DNA events",
  description: "List upcoming public events on the DNA platform (Convene module). Optionally filter by keyword.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Optional keyword filter (title/description)."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const n = limit ?? 10;
    let path = `events?select=id,title,description,start_time,end_time,location,event_type,slug&start_time=gte.${nowIso}&order=start_time.asc&limit=${n}`;
    if (query) {
      const q = encodeURIComponent(query);
      path += `&or=(title.ilike.*${q}*,description.ilike.*${q}*)`;
    }
    const res = await fetch(`${url}/rest/v1/${path}`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Supabase error ${res.status}: ${await res.text()}` }],
        isError: true
      };
    }
    const rows = await res.json();
    const results = rows.map((r) => ({
      ...r,
      event_url: r.slug ? `https://diasporanetwork.africa/dna/events/${r.slug}` : `https://diasporanetwork.africa/dna/events/${r.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get DNA profile by username",
  description: "Fetch a single public DNA member profile by username (the /dna/<username> handle).",
  inputSchema: {
    username: z3.string().trim().min(1).describe("The DNA username, without the leading @ or /dna/.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ username }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const uname = encodeURIComponent(username.replace(/^@/, ""));
    const path = `profiles?select=username,full_name,headline,bio,avatar_url,city,country,website_url&username=eq.${uname}&limit=1`;
    const res = await fetch(`${url}/rest/v1/${path}`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Supabase error ${res.status}: ${await res.text()}` }],
        isError: true
      };
    }
    const rows = await res.json();
    if (rows.length === 0) {
      return { content: [{ type: "text", text: `No profile found for @${username}` }], isError: true };
    }
    const profile = {
      ...rows[0],
      profile_url: `https://diasporanetwork.africa/dna/${rows[0].username}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dna-platform-mcp",
  title: "DNA (Diaspora Network of Africa)",
  version: "0.1.0",
  instructions: "Tools for exploring the DNA platform \u2014 the operating system for the Global African Diaspora. Use `search_profiles` and `get_profile` to look up public member profiles (shareable at /dna/<username>), and `list_upcoming_events` to discover upcoming public events across the Convene module. All tools return public data only.",
  tools: [search_profiles_default, get_profile_default, list_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
